DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  ADRESS VARCHAR(250) NOT NULL,
  BIRTH_DATE VARCHAR(250) NOT NULL,
  PHONE_NUMBER INT NOT NULL
);
